using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_BiomeMaterials")]
public partial class M_BiomeMaterials : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4649947552330352983UL,13530387805308431750UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public UnityEngine.Material f_BaseMat
	{
		get
		{
			return _f_BaseMat[Entity.Index];
		}
	}
	public UnityEngine.ScriptableObject f_BiomeMatData
	{
		get
		{
			return _f_BiomeMatData[Entity.Index];
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4978891958627373064UL,9403543406811406215UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityMaterial __f_BaseMat;
	public static BansheeGz.BGDatabase.BGFieldUnityMaterial _f_BaseMat
	{
		get
		{
			if(__f_BaseMat==null || __f_BaseMat.IsDeleted) __f_BaseMat=(BansheeGz.BGDatabase.BGFieldUnityMaterial) MetaDefault.GetField(new BGId(5644313148071272613UL,4942721971229058439UL));
			return __f_BaseMat;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_BiomeMatData;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_BiomeMatData
	{
		get
		{
			if(__f_BiomeMatData==null || __f_BiomeMatData.IsDeleted) __f_BiomeMatData=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(5687714982544646833UL,9757857676103977126UL));
			return __f_BiomeMatData;
		}
	}
}
