using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Pin = E_Pin;
using Alias_rifegrt_BiomeGameplayData = E_BiomeGameplayData;
using Alias_rifegrt_MapBiomeIdentifier = E_MapBiomeIdentifier;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Biome")]
public partial class M_Biome : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5318121685371950766UL,2942031341061376408UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 f_MinMaxX
	{
		get
		{
			return _f_MinMaxX[Entity.Index];
		}
		set
		{
			_f_MinMaxX[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector2 f_MinMaxZ
	{
		get
		{
			return _f_MinMaxZ[Entity.Index];
		}
		set
		{
			_f_MinMaxZ[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4811910356762317652UL,6316590992709792654UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __f_MinMaxX;
	public static BansheeGz.BGDatabase.BGFieldVector2 _f_MinMaxX
	{
		get
		{
			if(__f_MinMaxX==null || __f_MinMaxX.IsDeleted) __f_MinMaxX=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5540830184506237896UL,8565432699577718708UL));
			return __f_MinMaxX;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector2 __f_MinMaxZ;
	public static BansheeGz.BGDatabase.BGFieldVector2 _f_MinMaxZ
	{
		get
		{
			if(__f_MinMaxZ==null || __f_MinMaxZ.IsDeleted) __f_MinMaxZ=(BansheeGz.BGDatabase.BGFieldVector2) MetaDefault.GetField(new BGId(5028550124850018592UL,7548933405663777956UL));
			return __f_MinMaxZ;
		}
	}
	private static readonly List<BGEntity> _tugjbyuhfv_reusableList = new List<BGEntity>();
	public List<E_Pin> RelatedPinListUsingBiomeRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_Pin._f_Biome.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_Pin>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_Pin) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
	public List<E_BiomeGameplayData> RelatedBiomeGameplayDataListUsingBiomeRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_BiomeGameplayData._f_Biome.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_BiomeGameplayData>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_BiomeGameplayData) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
	public List<E_MapBiomeIdentifier> RelatedMapBiomeIdentifierListUsingBiomeRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_MapBiomeIdentifier._f_Biome.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_MapBiomeIdentifier>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_MapBiomeIdentifier) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
}
