using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Segments = E_Segments;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Dialogues")]
public partial class M_Dialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5691908276886008238UL,14353315125813875389UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Segments f_Segment
	{
		get
		{
			return (E_Segments) _f_Segment[Entity.Index];
		}
		set
		{
			_f_Segment[Entity.Index] = value;
		}
	}
	public UnityEngine.ScriptableObject f_RescueDialogue
	{
		get
		{
			return _f_RescueDialogue[Entity.Index];
		}
	}
	public List<E_QuestDialogues> f_QuestDialogues
	{
		get
		{
			var val = _f_QuestDialogues[Entity.Index];
			if(val==null || val.Count==0) return null;
			var ___QuestDialogues = new List<E_QuestDialogues>();
			for (var i = 0; i < val.Count; i++) ___QuestDialogues.Add((E_QuestDialogues) val[i]);
			return ___QuestDialogues;
		}
	}
	public List<E_QuestWaitingDialogues> f_QuestWaitingDialogues
	{
		get
		{
			var val = _f_QuestWaitingDialogues[Entity.Index];
			if(val==null || val.Count==0) return null;
			var ___QuestWaitingDialogues = new List<E_QuestWaitingDialogues>();
			for (var i = 0; i < val.Count; i++) ___QuestWaitingDialogues.Add((E_QuestWaitingDialogues) val[i]);
			return ___QuestWaitingDialogues;
		}
	}
	public List<E_ReturnDialogues> f_ReturnDialogues
	{
		get
		{
			var val = _f_ReturnDialogues[Entity.Index];
			if(val==null || val.Count==0) return null;
			var ___ReturnDialogues = new List<E_ReturnDialogues>();
			for (var i = 0; i < val.Count; i++) ___ReturnDialogues.Add((E_ReturnDialogues) val[i]);
			return ___ReturnDialogues;
		}
	}
	public List<E_AdditionalDialogues> f_AdditionalDialogues
	{
		get
		{
			var val = _f_AdditionalDialogues[Entity.Index];
			if(val==null || val.Count==0) return null;
			var ___AdditionalDialogues = new List<E_AdditionalDialogues>();
			for (var i = 0; i < val.Count; i++) ___AdditionalDialogues.Add((E_AdditionalDialogues) val[i]);
			return ___AdditionalDialogues;
		}
	}
	public List<E_HintsDialogues> f_HintsDialogues
	{
		get
		{
			var val = _f_HintsDialogues[Entity.Index];
			if(val==null || val.Count==0) return null;
			var ___HintsDialogues = new List<E_HintsDialogues>();
			for (var i = 0; i < val.Count; i++) ___HintsDialogues.Add((E_HintsDialogues) val[i]);
			return ___HintsDialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5300970025127205706UL,3063305633938667929UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Segment;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Segment
	{
		get
		{
			if(__f_Segment==null || __f_Segment.IsDeleted) __f_Segment=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5362655967193847021UL,8794766217772961702UL));
			return __f_Segment;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_RescueDialogue;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_RescueDialogue
	{
		get
		{
			if(__f_RescueDialogue==null || __f_RescueDialogue.IsDeleted) __f_RescueDialogue=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(5658430206875923811UL,17589914016796226975UL));
			return __f_RescueDialogue;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldNested __f_QuestDialogues;
	public static BansheeGz.BGDatabase.BGFieldNested _f_QuestDialogues
	{
		get
		{
			if(__f_QuestDialogues==null || __f_QuestDialogues.IsDeleted) __f_QuestDialogues=(BansheeGz.BGDatabase.BGFieldNested) MetaDefault.GetField(new BGId(5283433954133549919UL,4931491506496442543UL));
			return __f_QuestDialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldNested __f_QuestWaitingDialogues;
	public static BansheeGz.BGDatabase.BGFieldNested _f_QuestWaitingDialogues
	{
		get
		{
			if(__f_QuestWaitingDialogues==null || __f_QuestWaitingDialogues.IsDeleted) __f_QuestWaitingDialogues=(BansheeGz.BGDatabase.BGFieldNested) MetaDefault.GetField(new BGId(5428041660786546183UL,4300236321036646299UL));
			return __f_QuestWaitingDialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldNested __f_ReturnDialogues;
	public static BansheeGz.BGDatabase.BGFieldNested _f_ReturnDialogues
	{
		get
		{
			if(__f_ReturnDialogues==null || __f_ReturnDialogues.IsDeleted) __f_ReturnDialogues=(BansheeGz.BGDatabase.BGFieldNested) MetaDefault.GetField(new BGId(5510717961828634056UL,9806892908304910006UL));
			return __f_ReturnDialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldNested __f_AdditionalDialogues;
	public static BansheeGz.BGDatabase.BGFieldNested _f_AdditionalDialogues
	{
		get
		{
			if(__f_AdditionalDialogues==null || __f_AdditionalDialogues.IsDeleted) __f_AdditionalDialogues=(BansheeGz.BGDatabase.BGFieldNested) MetaDefault.GetField(new BGId(5650391854847053935UL,9041473667705462207UL));
			return __f_AdditionalDialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldNested __f_HintsDialogues;
	public static BansheeGz.BGDatabase.BGFieldNested _f_HintsDialogues
	{
		get
		{
			if(__f_HintsDialogues==null || __f_HintsDialogues.IsDeleted) __f_HintsDialogues=(BansheeGz.BGDatabase.BGFieldNested) MetaDefault.GetField(new BGId(4758135799136454102UL,13727966505551805077UL));
			return __f_HintsDialogues;
		}
	}
	private static readonly List<BGEntity> _tugjbyuhfv_reusableList = new List<BGEntity>();
	public List<E_Segments> RelatedSegmentsListUsingDialoguesRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_Segments._f_Dialogues.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_Segments>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_Segments) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
}
