using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_FluffDialogues")]
public partial class M_FluffDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5501167370060631032UL,10787851089245723537UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Dialogues f_Dialogues
	{
		get
		{
			return (E_Dialogues) _f_Dialogues[Entity.Index];
		}
		set
		{
			_f_Dialogues[Entity.Index] = value;
		}
	}
	public UnityEngine.ScriptableObject f_FluffDialogue
	{
		get
		{
			return _f_FluffDialogue[Entity.Index];
		}
	}
	public E_FluffDialogueGameplayData f_GameplayData
	{
		get
		{
			return (E_FluffDialogueGameplayData) _f_GameplayData[Entity.Index];
		}
		set
		{
			_f_GameplayData[Entity.Index] = value;
		}
	}
	public System.Boolean f_Played
	{
		get
		{
			return _f_Played[Entity.Index];
		}
		set
		{
			_f_Played[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4678961077541721324UL,18130792169655123106UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues
	{
		get
		{
			if(__f_Dialogues==null || __f_Dialogues.IsDeleted) __f_Dialogues=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5025612804227916872UL,6154068310714723463UL));
			return __f_Dialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_FluffDialogue;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_FluffDialogue
	{
		get
		{
			if(__f_FluffDialogue==null || __f_FluffDialogue.IsDeleted) __f_FluffDialogue=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(5022444791640245293UL,3339558332882937501UL));
			return __f_FluffDialogue;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_GameplayData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_GameplayData
	{
		get
		{
			if(__f_GameplayData==null || __f_GameplayData.IsDeleted) __f_GameplayData=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5366881371379425601UL,3453028088459494838UL));
			return __f_GameplayData;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool __f_Played;
	public static BansheeGz.BGDatabase.BGFieldBool _f_Played
	{
		get
		{
			if(__f_Played==null || __f_Played.IsDeleted) __f_Played=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5547494182720534484UL,12540949173131056551UL));
			return __f_Played;
		}
	}
}
