using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_FluffDialogue")]
public partial class M_FluffDialogue : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5761198108724242759UL,15962685899360488851UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_FluffDialogues f_FluffDialogues
	{
		get => (E_FluffDialogues) _f_FluffDialogues[Entity.Index];
		set => _f_FluffDialogues[Entity.Index] = value;
	}
	public System.Int32 f_CharIndex
	{
		get => _f_CharIndex[Entity.Index];
		set => _f_CharIndex[Entity.Index] = value;
	}
	public Expressions f_Expression
	{
		get => (Expressions) _f_Expression[Entity.Index];
		set => _f_Expression[Entity.Index] = value;
	}
	public System.String f_LocalizedText
	{
		get => _f_LocalizedText[Entity.Index];
		set => _f_LocalizedText[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5567906099477920680UL, 17953357142608853403UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_FluffDialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_FluffDialogues => _ufle12jhs77_f_FluffDialogues ?? (_ufle12jhs77_f_FluffDialogues = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4635260982999077520UL, 17823775534033834893UL), () => _ufle12jhs77_f_FluffDialogues = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_CharIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _f_CharIndex => _ufle12jhs77_f_CharIndex ?? (_ufle12jhs77_f_CharIndex = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5219876258038993031UL, 13349531508774759827UL), () => _ufle12jhs77_f_CharIndex = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Expression;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Expression => _ufle12jhs77_f_Expression ?? (_ufle12jhs77_f_Expression = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5102869862866527441UL, 6610166580539208118UL), () => _ufle12jhs77_f_Expression = null));
	private static BansheeGz.BGDatabase.BGFieldLocalizedText _ufle12jhs77_f_LocalizedText;
	public static BansheeGz.BGDatabase.BGFieldLocalizedText _f_LocalizedText => _ufle12jhs77_f_LocalizedText ?? (_ufle12jhs77_f_LocalizedText = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocalizedText>(MetaDefault, new BGId(5655427299389013229UL, 10875540640639273911UL), () => _ufle12jhs77_f_LocalizedText = null));
}
