using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_InGameDialogues")]
public partial class M_InGameDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5428396456083422956UL,7527115826262989197UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Dialogues f_Dialogues
	{
		get => (E_Dialogues) _f_Dialogues[Entity.Index];
		set => _f_Dialogues[Entity.Index] = value;
	}
	public List<E_InGameDialogue> f_InGameDialogue => BGCodeGenUtils.GetNested<E_InGameDialogue>(_f_InGameDialogue, Entity.Index);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5741115015081026209UL, 3870164971529372299UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues => _ufle12jhs77_f_Dialogues ?? (_ufle12jhs77_f_Dialogues = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5198211926063270700UL, 17504916394894263943UL), () => _ufle12jhs77_f_Dialogues = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_InGameDialogue;
	public static BansheeGz.BGDatabase.BGFieldNested _f_InGameDialogue => _ufle12jhs77_f_InGameDialogue ?? (_ufle12jhs77_f_InGameDialogue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5240724613128142100UL, 10538712851917267356UL), () => _ufle12jhs77_f_InGameDialogue = null));
}
