using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_LevelData")]
public partial class M_LevelData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4612244309294333557UL,1881374458602735547UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Pin f_Pin
	{
		get => (E_Pin) _f_Pin[Entity.Index];
		set => _f_Pin[Entity.Index] = value;
	}
	public System.String f_Level
	{
		get => _f_Level[Entity.Index];
		set => _f_Level[Entity.Index] = value;
	}
	public System.Boolean f_InMap
	{
		get => _f_InMap[Entity.Index];
		set => _f_InMap[Entity.Index] = value;
	}
	public System.Int32 f_LocksAmount
	{
		get => _f_LocksAmount[Entity.Index];
		set => _f_LocksAmount[Entity.Index] = value;
	}
	public System.Boolean f_SegmentPresent
	{
		get => _f_SegmentPresent[Entity.Index];
		set => _f_SegmentPresent[Entity.Index] = value;
	}
	public System.Boolean f_ObjectPresent
	{
		get => _f_ObjectPresent[Entity.Index];
		set => _f_ObjectPresent[Entity.Index] = value;
	}
	public List<E_Pin> f_UnlocksPins
	{
		get => BGCodeGenUtils.MultipleRelationGet<E_Pin>(_f_UnlocksPins, Entity.Index);
		set => BGCodeGenUtils.MultipleRelationSet<E_Pin>(_f_UnlocksPins, Entity.Index, value);
	}
	public List<E_MapWalls> f_WallsToDest
	{
		get => BGCodeGenUtils.MultipleRelationGet<E_MapWalls>(_f_WallsToDest, Entity.Index);
		set => BGCodeGenUtils.MultipleRelationSet<E_MapWalls>(_f_WallsToDest, Entity.Index, value);
	}
	public List<E_MapWalls> f_WallsFromOrigin
	{
		get => BGCodeGenUtils.MultipleRelationGet<E_MapWalls>(_f_WallsFromOrigin, Entity.Index);
		set => BGCodeGenUtils.MultipleRelationSet<E_MapWalls>(_f_WallsFromOrigin, Entity.Index, value);
	}
	public System.Boolean f_Visuals
	{
		get => _f_Visuals[Entity.Index];
		set => _f_Visuals[Entity.Index] = value;
	}
	public E_Objects f_ForceObject
	{
		get => (E_Objects) _f_ForceObject[Entity.Index];
		set => _f_ForceObject[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4740419652275606489UL, 16281884087163071164UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Pin;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Pin => _ufle12jhs77_f_Pin ?? (_ufle12jhs77_f_Pin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4755775874130559592UL, 9555642772104298655UL), () => _ufle12jhs77_f_Pin = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Level;
	public static BansheeGz.BGDatabase.BGFieldString _f_Level => _ufle12jhs77_f_Level ?? (_ufle12jhs77_f_Level = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4793347658190675977UL, 5994557562632312988UL), () => _ufle12jhs77_f_Level = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_InMap;
	public static BansheeGz.BGDatabase.BGFieldBool _f_InMap => _ufle12jhs77_f_InMap ?? (_ufle12jhs77_f_InMap = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4858229157076024160UL, 2433292969023106195UL), () => _ufle12jhs77_f_InMap = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_LocksAmount;
	public static BansheeGz.BGDatabase.BGFieldInt _f_LocksAmount => _ufle12jhs77_f_LocksAmount ?? (_ufle12jhs77_f_LocksAmount = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5389772333846653446UL, 11461131677490296486UL), () => _ufle12jhs77_f_LocksAmount = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_SegmentPresent;
	public static BansheeGz.BGDatabase.BGFieldBool _f_SegmentPresent => _ufle12jhs77_f_SegmentPresent ?? (_ufle12jhs77_f_SegmentPresent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5708768082108931619UL, 17251627778783522965UL), () => _ufle12jhs77_f_SegmentPresent = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_ObjectPresent;
	public static BansheeGz.BGDatabase.BGFieldBool _f_ObjectPresent => _ufle12jhs77_f_ObjectPresent ?? (_ufle12jhs77_f_ObjectPresent = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5035583959570880310UL, 15876700667616842681UL), () => _ufle12jhs77_f_ObjectPresent = null));
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_f_UnlocksPins;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _f_UnlocksPins => _ufle12jhs77_f_UnlocksPins ?? (_ufle12jhs77_f_UnlocksPins = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(5421760005998256390UL, 4758386679893286829UL), () => _ufle12jhs77_f_UnlocksPins = null));
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_f_WallsToDest;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _f_WallsToDest => _ufle12jhs77_f_WallsToDest ?? (_ufle12jhs77_f_WallsToDest = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(5242919301705000379UL, 3930519681876219828UL), () => _ufle12jhs77_f_WallsToDest = null));
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_f_WallsFromOrigin;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _f_WallsFromOrigin => _ufle12jhs77_f_WallsFromOrigin ?? (_ufle12jhs77_f_WallsFromOrigin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(5300666196508900259UL, 13485411823914233985UL), () => _ufle12jhs77_f_WallsFromOrigin = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_Visuals;
	public static BansheeGz.BGDatabase.BGFieldBool _f_Visuals => _ufle12jhs77_f_Visuals ?? (_ufle12jhs77_f_Visuals = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5556000267342264102UL, 15804675842545476242UL), () => _ufle12jhs77_f_Visuals = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_ForceObject;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_ForceObject => _ufle12jhs77_f_ForceObject ?? (_ufle12jhs77_f_ForceObject = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5492051446524140481UL, 7396505186639121819UL), () => _ufle12jhs77_f_ForceObject = null));
}
