using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Localization")]
public partial class M_Localization : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaLocalizationSettings _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaLocalizationSettings MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaLocalizationSettings>(new BGId(5432925538614801938UL,6334591579126931072UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public List<E_Locale> f_Locale => BGCodeGenUtils.GetNested<E_Locale>(_f_Locale, Entity.Index);
	public E_Locale f_current
	{
		get => (E_Locale) _f_current[Entity.Index];
		set => _f_current[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5702000873616785347UL, 6103800249142544278UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_Locale;
	public static BansheeGz.BGDatabase.BGFieldNested _f_Locale => _ufle12jhs77_f_Locale ?? (_ufle12jhs77_f_Locale = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5572038467975061259UL, 5847152299141113776UL), () => _ufle12jhs77_f_Locale = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_current;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_current => _ufle12jhs77_f_current ?? (_ufle12jhs77_f_current = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4963999306482294263UL, 3642996081275348621UL), () => _ufle12jhs77_f_current = null));
}
