using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Loca_InGameDialogue")]
public partial class M_Loca_InGameDialogue : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaLocalization _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaLocalization MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaLocalization>(new BGId(5682398989620032364UL,1339760119320202677UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.String f_english
	{
		get => _f_english[Entity.Index];
		set => _f_english[Entity.Index] = value;
	}
	public System.String f_spanish
	{
		get => _f_spanish[Entity.Index];
		set => _f_spanish[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4909345426842346038UL, 16569541639165942939UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldLocaleText _ufle12jhs77_f_english;
	public static BansheeGz.BGDatabase.BGFieldLocaleText _f_english => _ufle12jhs77_f_english ?? (_ufle12jhs77_f_english = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocaleText>(MetaDefault, new BGId(5557832927087833749UL, 4994364790227243400UL), () => _ufle12jhs77_f_english = null));
	private static BansheeGz.BGDatabase.BGFieldLocaleText _ufle12jhs77_f_spanish;
	public static BansheeGz.BGDatabase.BGFieldLocaleText _f_spanish => _ufle12jhs77_f_spanish ?? (_ufle12jhs77_f_spanish = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocaleText>(MetaDefault, new BGId(5427861261852927151UL, 10783830716513093762UL), () => _ufle12jhs77_f_spanish = null));
	public System.String LocalizedValue
	{
		get => MetaDefault.GetField<System.String>(BGAddonLocalization.DefaultRepoCurrentLocale)[Entity.Index];
		set => MetaDefault.GetField<System.String>(BGAddonLocalization.DefaultRepoCurrentLocale)[Entity.Index] = value;
	}
}
