using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Loca_ReturnDialogues")]
public partial class M_Loca_ReturnDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaLocalization _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaLocalization MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaLocalization>(new BGId(5176751877220807342UL,7531992378373811884UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.String f_English
	{
		get => _f_English[Entity.Index];
		set => _f_English[Entity.Index] = value;
	}
	public System.String f_Spanish
	{
		get => _f_Spanish[Entity.Index];
		set => _f_Spanish[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5190627662475483092UL, 14790807011160082827UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldLocaleText _ufle12jhs77_f_English;
	public static BansheeGz.BGDatabase.BGFieldLocaleText _f_English => _ufle12jhs77_f_English ?? (_ufle12jhs77_f_English = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocaleText>(MetaDefault, new BGId(4793910002518806795UL, 17015621422092107416UL), () => _ufle12jhs77_f_English = null));
	private static BansheeGz.BGDatabase.BGFieldLocaleText _ufle12jhs77_f_Spanish;
	public static BansheeGz.BGDatabase.BGFieldLocaleText _f_Spanish => _ufle12jhs77_f_Spanish ?? (_ufle12jhs77_f_Spanish = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocaleText>(MetaDefault, new BGId(4942591586809596762UL, 16226444070095516579UL), () => _ufle12jhs77_f_Spanish = null));
	public System.String LocalizedValue
	{
		get => MetaDefault.GetField<System.String>(BGAddonLocalization.DefaultRepoCurrentLocale)[Entity.Index];
		set => MetaDefault.GetField<System.String>(BGAddonLocalization.DefaultRepoCurrentLocale)[Entity.Index] = value;
	}
}
