using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Localization = E_Localization;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Locale")]
public partial class M_Locale : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5507787881602784516UL,6166370465318004876UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Localization f_Localization
	{
		get => (E_Localization) _f_Localization[Entity.Index];
		set => _f_Localization[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4792653790126608343UL, 7633147314493927066UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Localization;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Localization => _ufle12jhs77_f_Localization ?? (_ufle12jhs77_f_Localization = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4893124971542260402UL, 6702503202722724279UL), () => _ufle12jhs77_f_Localization = null));
	public List<Alias_rifegrt_Localization> RelatedLocalizationListUsingcurrentRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Localization>(Alias_rifegrt_Localization._f_current, Entity.Id);
}
