using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_LevelData = E_LevelData;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_MapWalls")]
public partial class M_MapWalls : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4959565327689654965UL,2471908366607778707UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Pin f_OriginPin
	{
		get => (E_Pin) _f_OriginPin[Entity.Index];
		set => _f_OriginPin[Entity.Index] = value;
	}
	public E_Pin f_DestPin
	{
		get => (E_Pin) _f_DestPin[Entity.Index];
		set => _f_DestPin[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5712327967688250671UL, 6283100240849974687UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_OriginPin;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_OriginPin => _ufle12jhs77_f_OriginPin ?? (_ufle12jhs77_f_OriginPin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4679121713698528948UL, 1872479915702842775UL), () => _ufle12jhs77_f_OriginPin = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_DestPin;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_DestPin => _ufle12jhs77_f_DestPin ?? (_ufle12jhs77_f_DestPin = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5682693562927262261UL, 886020703537969570UL), () => _ufle12jhs77_f_DestPin = null));
	public List<Alias_rifegrt_LevelData> RelatedLevelDataListUsingWallsToDestRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelData>(Alias_rifegrt_LevelData._f_WallsToDest, Entity.Id);
	public List<Alias_rifegrt_LevelData> RelatedLevelDataListUsingWallsFromOriginRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelData>(Alias_rifegrt_LevelData._f_WallsFromOrigin, Entity.Id);
}
