using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Objects")]
public partial class M_Objects : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4871657982410721797UL,750137968299760546UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public UnityEngine.GameObject f_Prefab
	{
		get
		{
			return _f_Prefab[Entity.Index];
		}
	}
	public E_Segments f_Owner
	{
		get
		{
			return (E_Segments) _f_Owner[Entity.Index];
		}
		set
		{
			_f_Owner[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5270256987534184595UL,7271033944239394211UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab __f_Prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _f_Prefab
	{
		get
		{
			if(__f_Prefab==null || __f_Prefab.IsDeleted) __f_Prefab=(BansheeGz.BGDatabase.BGFieldUnityPrefab) MetaDefault.GetField(new BGId(4702383594286821901UL,9980623028393390773UL));
			return __f_Prefab;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Owner;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Owner
	{
		get
		{
			if(__f_Owner==null || __f_Owner.IsDeleted) __f_Owner=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5020747016533988793UL,12419271386286385327UL));
			return __f_Owner;
		}
	}
}
