using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_LevelData = E_LevelData;
using Alias_rifegrt_Segments = E_Segments;
using Alias_rifegrt_ReturnDialogues = E_ReturnDialogues;
using Alias_rifegrt_ObjectsGameplayData = E_ObjectsGameplayData;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Objects")]
public partial class M_Objects : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4871657982410721797UL,750137968299760546UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.String f_ObjectTitle
	{
		get => _f_ObjectTitle[Entity.Index];
		set => _f_ObjectTitle[Entity.Index] = value;
	}
	public System.String f_ObjectSubText
	{
		get => _f_ObjectSubText[Entity.Index];
		set => _f_ObjectSubText[Entity.Index] = value;
	}
	public UnityEngine.GameObject f_Prefab => _f_Prefab[Entity.Index];
	public E_Segments f_Owner
	{
		get => (E_Segments) _f_Owner[Entity.Index];
		set => _f_Owner[Entity.Index] = value;
	}
	public E_ObjectsGameplayData f_GameplayData
	{
		get => (E_ObjectsGameplayData) _f_GameplayData[Entity.Index];
		set => _f_GameplayData[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5270256987534184595UL, 7271033944239394211UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_ObjectTitle;
	public static BansheeGz.BGDatabase.BGFieldString _f_ObjectTitle => _ufle12jhs77_f_ObjectTitle ?? (_ufle12jhs77_f_ObjectTitle = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5394372170959802640UL, 9009507287611560632UL), () => _ufle12jhs77_f_ObjectTitle = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_ObjectSubText;
	public static BansheeGz.BGDatabase.BGFieldString _f_ObjectSubText => _ufle12jhs77_f_ObjectSubText ?? (_ufle12jhs77_f_ObjectSubText = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5594065245607900864UL, 6912274191189485987UL), () => _ufle12jhs77_f_ObjectSubText = null));
	private static BansheeGz.BGDatabase.BGFieldUnityPrefab _ufle12jhs77_f_Prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityPrefab _f_Prefab => _ufle12jhs77_f_Prefab ?? (_ufle12jhs77_f_Prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityPrefab>(MetaDefault, new BGId(4702383594286821901UL, 9980623028393390773UL), () => _ufle12jhs77_f_Prefab = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Owner;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Owner => _ufle12jhs77_f_Owner ?? (_ufle12jhs77_f_Owner = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5020747016533988793UL, 12419271386286385327UL), () => _ufle12jhs77_f_Owner = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_GameplayData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_GameplayData => _ufle12jhs77_f_GameplayData ?? (_ufle12jhs77_f_GameplayData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5680102043031229158UL, 4949064207623274920UL), () => _ufle12jhs77_f_GameplayData = null));
	public List<Alias_rifegrt_LevelData> RelatedLevelDataListUsingForceObjectRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelData>(Alias_rifegrt_LevelData._f_ForceObject, Entity.Id);
	public List<Alias_rifegrt_Segments> RelatedSegmentsListUsingObjectsRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Segments>(Alias_rifegrt_Segments._f_Objects, Entity.Id);
	public List<Alias_rifegrt_ReturnDialogues> RelatedReturnDialoguesListUsingForObjectRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_ReturnDialogues>(Alias_rifegrt_ReturnDialogues._f_ForObject, Entity.Id);
	public List<Alias_rifegrt_ObjectsGameplayData> RelatedObjectsGameplayDataListUsingObjectRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_ObjectsGameplayData>(Alias_rifegrt_ObjectsGameplayData._f_Object, Entity.Id);
}
