using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Objects = E_Objects;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_ObjectsGameplayData")]
public partial class M_ObjectsGameplayData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4658376294490806110UL,6950373328361257866UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Objects f_Object
	{
		get => (E_Objects) _f_Object[Entity.Index];
		set => _f_Object[Entity.Index] = value;
	}
	public System.Boolean f_ObjectFound
	{
		get => _f_ObjectFound[Entity.Index];
		set => _f_ObjectFound[Entity.Index] = value;
	}
	public System.Boolean f_ObjectReturned
	{
		get => _f_ObjectReturned[Entity.Index];
		set => _f_ObjectReturned[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4704137733006346466UL, 6507642195071752856UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Object;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Object => _ufle12jhs77_f_Object ?? (_ufle12jhs77_f_Object = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5575310436151618600UL, 1591952302039477673UL), () => _ufle12jhs77_f_Object = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_ObjectFound;
	public static BansheeGz.BGDatabase.BGFieldBool _f_ObjectFound => _ufle12jhs77_f_ObjectFound ?? (_ufle12jhs77_f_ObjectFound = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5418712494444133144UL, 10507902628022803586UL), () => _ufle12jhs77_f_ObjectFound = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_ObjectReturned;
	public static BansheeGz.BGDatabase.BGFieldBool _f_ObjectReturned => _ufle12jhs77_f_ObjectReturned ?? (_ufle12jhs77_f_ObjectReturned = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4762361548636797324UL, 11593070393711443599UL), () => _ufle12jhs77_f_ObjectReturned = null));
	public List<Alias_rifegrt_Objects> RelatedObjectsListUsingGameplayDataRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Objects>(Alias_rifegrt_Objects._f_GameplayData, Entity.Id);
}
