using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Obj1ReturnDialogue")]
public partial class M_Obj1ReturnDialogue : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5551337380290394530UL,11303734052572149401UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_ReturnDialogues f_ReturnDialogues
	{
		get => (E_ReturnDialogues) _f_ReturnDialogues[Entity.Index];
		set => _f_ReturnDialogues[Entity.Index] = value;
	}
	public System.Int32 f_CharIndex
	{
		get => _f_CharIndex[Entity.Index];
		set => _f_CharIndex[Entity.Index] = value;
	}
	public Expressions f_Expression
	{
		get => (Expressions) _f_Expression[Entity.Index];
		set => _f_Expression[Entity.Index] = value;
	}
	public System.String f_LocalizedText
	{
		get => _f_LocalizedText[Entity.Index];
		set => _f_LocalizedText[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5135408982142864977UL, 18342341157639807405UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_ReturnDialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_ReturnDialogues => _ufle12jhs77_f_ReturnDialogues ?? (_ufle12jhs77_f_ReturnDialogues = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5612075101515907512UL, 3522637337558372276UL), () => _ufle12jhs77_f_ReturnDialogues = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_CharIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _f_CharIndex => _ufle12jhs77_f_CharIndex ?? (_ufle12jhs77_f_CharIndex = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5652317368442813160UL, 4024215222169479040UL), () => _ufle12jhs77_f_CharIndex = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_Expression;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_Expression => _ufle12jhs77_f_Expression ?? (_ufle12jhs77_f_Expression = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(5253706905638534847UL, 16663669682411776919UL), () => _ufle12jhs77_f_Expression = null));
	private static BansheeGz.BGDatabase.BGFieldLocalizedText _ufle12jhs77_f_LocalizedText;
	public static BansheeGz.BGDatabase.BGFieldLocalizedText _f_LocalizedText => _ufle12jhs77_f_LocalizedText ?? (_ufle12jhs77_f_LocalizedText = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldLocalizedText>(MetaDefault, new BGId(4833622354798815220UL, 4969987681529896084UL), () => _ufle12jhs77_f_LocalizedText = null));
}
