using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_LevelData = E_LevelData;
using Alias_rifegrt_LevelGameplayData = E_LevelGameplayData;
using Alias_rifegrt_MapWalls = E_MapWalls;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Pin")]
public partial class M_Pin : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4954953875072214365UL,15478807282525472406UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Biome f_Biome
	{
		get => (E_Biome) _f_Biome[Entity.Index];
		set => _f_Biome[Entity.Index] = value;
	}
	public System.Int32 f_Index
	{
		get => _f_Index[Entity.Index];
		set => _f_Index[Entity.Index] = value;
	}
	public System.Int32 f_PinTextUI
	{
		get => _f_PinTextUI[Entity.Index];
		set => _f_PinTextUI[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5700619351467592780UL, 9596716367873031603UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Biome;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Biome => _ufle12jhs77_f_Biome ?? (_ufle12jhs77_f_Biome = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5355639157912867324UL, 1763305154346170539UL), () => _ufle12jhs77_f_Biome = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_Index;
	public static BansheeGz.BGDatabase.BGFieldInt _f_Index => _ufle12jhs77_f_Index ?? (_ufle12jhs77_f_Index = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5713392823763091186UL, 10906278620831617424UL), () => _ufle12jhs77_f_Index = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_PinTextUI;
	public static BansheeGz.BGDatabase.BGFieldInt _f_PinTextUI => _ufle12jhs77_f_PinTextUI ?? (_ufle12jhs77_f_PinTextUI = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5208647534428573803UL, 268406907975443346UL), () => _ufle12jhs77_f_PinTextUI = null));
	public List<Alias_rifegrt_LevelData> RelatedLevelDataListUsingPinRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelData>(Alias_rifegrt_LevelData._f_Pin, Entity.Id);
	public List<Alias_rifegrt_LevelData> RelatedLevelDataListUsingUnlocksPinsRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelData>(Alias_rifegrt_LevelData._f_UnlocksPins, Entity.Id);
	public List<Alias_rifegrt_LevelGameplayData> RelatedLevelGameplayDataListUsingPinRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_LevelGameplayData>(Alias_rifegrt_LevelGameplayData._f_Pin, Entity.Id);
	public List<Alias_rifegrt_MapWalls> RelatedMapWallsListUsingOriginPinRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_MapWalls>(Alias_rifegrt_MapWalls._f_OriginPin, Entity.Id);
	public List<Alias_rifegrt_MapWalls> RelatedMapWallsListUsingDestPinRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_MapWalls>(Alias_rifegrt_MapWalls._f_DestPin, Entity.Id);
}
