using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_QuestDialogues")]
public partial class M_QuestDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4808130919358401807UL,52346600882199431UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Dialogues f_Dialogues
	{
		get
		{
			return (E_Dialogues) _f_Dialogues[Entity.Index];
		}
		set
		{
			_f_Dialogues[Entity.Index] = value;
		}
	}
	public UnityEngine.ScriptableObject f_QuestDialogue
	{
		get
		{
			return _f_QuestDialogue[Entity.Index];
		}
	}
	public System.Boolean f_Played
	{
		get
		{
			return _f_Played[Entity.Index];
		}
		set
		{
			_f_Played[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5266780885273243854UL,4959441787887254671UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues
	{
		get
		{
			if(__f_Dialogues==null || __f_Dialogues.IsDeleted) __f_Dialogues=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5321635391406516302UL,10948997418535215012UL));
			return __f_Dialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_QuestDialogue;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_QuestDialogue
	{
		get
		{
			if(__f_QuestDialogue==null || __f_QuestDialogue.IsDeleted) __f_QuestDialogue=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(5688831178092183995UL,10495045604489321390UL));
			return __f_QuestDialogue;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool __f_Played;
	public static BansheeGz.BGDatabase.BGFieldBool _f_Played
	{
		get
		{
			if(__f_Played==null || __f_Played.IsDeleted) __f_Played=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5610891607708365715UL,14651620147662419376UL));
			return __f_Played;
		}
	}
}
