using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_ReturnDialogues")]
public partial class M_ReturnDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4870647987258873166UL,7601789944337567620UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Dialogues f_Dialogues
	{
		get => (E_Dialogues) _f_Dialogues[Entity.Index];
		set => _f_Dialogues[Entity.Index] = value;
	}
	public List<E_ReturnDialogue> f_ReturnDialogue => BGCodeGenUtils.GetNested<E_ReturnDialogue>(_f_ReturnDialogue, Entity.Index);
	public Expressions f_FirstExpr
	{
		get => (Expressions) _f_FirstExpr[Entity.Index];
		set => _f_FirstExpr[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5266760306252603425UL, 5886380830954584228UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues => _ufle12jhs77_f_Dialogues ?? (_ufle12jhs77_f_Dialogues = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5616062900662357611UL, 16901702900459328912UL), () => _ufle12jhs77_f_Dialogues = null));
	private static BansheeGz.BGDatabase.BGFieldNested _ufle12jhs77_f_ReturnDialogue;
	public static BansheeGz.BGDatabase.BGFieldNested _f_ReturnDialogue => _ufle12jhs77_f_ReturnDialogue ?? (_ufle12jhs77_f_ReturnDialogue = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldNested>(MetaDefault, new BGId(5007311056094085472UL, 12783879240225579182UL), () => _ufle12jhs77_f_ReturnDialogue = null));
	private static BansheeGz.BGDatabase.BGFieldEnum _ufle12jhs77_f_FirstExpr;
	public static BansheeGz.BGDatabase.BGFieldEnum _f_FirstExpr => _ufle12jhs77_f_FirstExpr ?? (_ufle12jhs77_f_FirstExpr = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEnum>(MetaDefault, new BGId(4945211625033104206UL, 12376233100031496112UL), () => _ufle12jhs77_f_FirstExpr = null));
}
