using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_ReturnDialogues")]
public partial class M_ReturnDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(4870647987258873166UL,7601789944337567620UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Dialogues f_Dialogues
	{
		get
		{
			return (E_Dialogues) _f_Dialogues[Entity.Index];
		}
		set
		{
			_f_Dialogues[Entity.Index] = value;
		}
	}
	public UnityEngine.ScriptableObject f_ReturnDialogue
	{
		get
		{
			return _f_ReturnDialogue[Entity.Index];
		}
	}
	public E_Objects f_ForObject
	{
		get
		{
			return (E_Objects) _f_ForObject[Entity.Index];
		}
		set
		{
			_f_ForObject[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5266760306252603425UL,5886380830954584228UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues
	{
		get
		{
			if(__f_Dialogues==null || __f_Dialogues.IsDeleted) __f_Dialogues=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5616062900662357611UL,16901702900459328912UL));
			return __f_Dialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_ReturnDialogue;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_ReturnDialogue
	{
		get
		{
			if(__f_ReturnDialogue==null || __f_ReturnDialogue.IsDeleted) __f_ReturnDialogue=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(5561073307789242631UL,2750474124636255876UL));
			return __f_ReturnDialogue;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_ForObject;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_ForObject
	{
		get
		{
			if(__f_ForObject==null || __f_ForObject.IsDeleted) __f_ForObject=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5205356440346579593UL,8967285530539706020UL));
			return __f_ForObject;
		}
	}
}
