using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Dialogues = E_Dialogues;
using Alias_rifegrt_SegmentsGameplayData = E_SegmentsGameplayData;
using Alias_rifegrt_Objects = E_Objects;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Segments")]
public partial class M_Segments : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5644026291501976503UL,5194951680243965827UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public System.String f_SegmentName
	{
		get => _f_SegmentName[Entity.Index];
		set => _f_SegmentName[Entity.Index] = value;
	}
	public UnityEngine.Object f_Prefab => _f_Prefab[Entity.Index];
	public List<E_Objects> f_Objects
	{
		get => BGCodeGenUtils.MultipleRelationGet<E_Objects>(_f_Objects, Entity.Index);
		set => BGCodeGenUtils.MultipleRelationSet<E_Objects>(_f_Objects, Entity.Index, value);
	}
	public E_Dialogues f_Dialogues
	{
		get => (E_Dialogues) _f_Dialogues[Entity.Index];
		set => _f_Dialogues[Entity.Index] = value;
	}
	public UnityEngine.Object f_SpawnPrefab => _f_SpawnPrefab[Entity.Index];
	public UnityEngine.Vector3 f_DialogueRotation
	{
		get => _f_DialogueRotation[Entity.Index];
		set => _f_DialogueRotation[Entity.Index] = value;
	}
	public UnityEngine.Vector3 f_InGameDialogueRotation
	{
		get => _f_InGameDialogueRotation[Entity.Index];
		set => _f_InGameDialogueRotation[Entity.Index] = value;
	}
	public UnityEngine.Vector2 f_DialogueLightPitchYaw
	{
		get => _f_DialogueLightPitchYaw[Entity.Index];
		set => _f_DialogueLightPitchYaw[Entity.Index] = value;
	}
	public UnityEngine.Vector2 f_InGameDialogueLightPitchYaw
	{
		get => _f_InGameDialogueLightPitchYaw[Entity.Index];
		set => _f_InGameDialogueLightPitchYaw[Entity.Index] = value;
	}
	public E_SegmentsGameplayData f_GameplayData
	{
		get => (E_SegmentsGameplayData) _f_GameplayData[Entity.Index];
		set => _f_GameplayData[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5670569073695034891UL, 14796031301428454317UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_SegmentName;
	public static BansheeGz.BGDatabase.BGFieldString _f_SegmentName => _ufle12jhs77_f_SegmentName ?? (_ufle12jhs77_f_SegmentName = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4705691430409051370UL, 10398669542945010076UL), () => _ufle12jhs77_f_SegmentName = null));
	private static BansheeGz.BGDatabase.BGFieldUnityObject _ufle12jhs77_f_Prefab;
	public static BansheeGz.BGDatabase.BGFieldUnityObject _f_Prefab => _ufle12jhs77_f_Prefab ?? (_ufle12jhs77_f_Prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityObject>(MetaDefault, new BGId(5042412784670426887UL, 3798303333898769295UL), () => _ufle12jhs77_f_Prefab = null));
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_f_Objects;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _f_Objects => _ufle12jhs77_f_Objects ?? (_ufle12jhs77_f_Objects = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(5414509257987170800UL, 16375924262376720830UL), () => _ufle12jhs77_f_Objects = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues => _ufle12jhs77_f_Dialogues ?? (_ufle12jhs77_f_Dialogues = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5043863872193162925UL, 15580842669602972338UL), () => _ufle12jhs77_f_Dialogues = null));
	private static BansheeGz.BGDatabase.BGFieldUnityObject _ufle12jhs77_f_SpawnPrefab;
	public static BansheeGz.BGDatabase.BGFieldUnityObject _f_SpawnPrefab => _ufle12jhs77_f_SpawnPrefab ?? (_ufle12jhs77_f_SpawnPrefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldUnityObject>(MetaDefault, new BGId(5584655967112634227UL, 13267101346744214414UL), () => _ufle12jhs77_f_SpawnPrefab = null));
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_f_DialogueRotation;
	public static BansheeGz.BGDatabase.BGFieldVector3 _f_DialogueRotation => _ufle12jhs77_f_DialogueRotation ?? (_ufle12jhs77_f_DialogueRotation = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector3>(MetaDefault, new BGId(5760607302971462463UL, 3672824699726006442UL), () => _ufle12jhs77_f_DialogueRotation = null));
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_f_InGameDialogueRotation;
	public static BansheeGz.BGDatabase.BGFieldVector3 _f_InGameDialogueRotation => _ufle12jhs77_f_InGameDialogueRotation ?? (_ufle12jhs77_f_InGameDialogueRotation = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector3>(MetaDefault, new BGId(4917617894530905501UL, 14489070524609965239UL), () => _ufle12jhs77_f_InGameDialogueRotation = null));
	private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_f_DialogueLightPitchYaw;
	public static BansheeGz.BGDatabase.BGFieldVector2 _f_DialogueLightPitchYaw => _ufle12jhs77_f_DialogueLightPitchYaw ?? (_ufle12jhs77_f_DialogueLightPitchYaw = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector2>(MetaDefault, new BGId(5395289116548682697UL, 15975294921309799602UL), () => _ufle12jhs77_f_DialogueLightPitchYaw = null));
	private static BansheeGz.BGDatabase.BGFieldVector2 _ufle12jhs77_f_InGameDialogueLightPitchYaw;
	public static BansheeGz.BGDatabase.BGFieldVector2 _f_InGameDialogueLightPitchYaw => _ufle12jhs77_f_InGameDialogueLightPitchYaw ?? (_ufle12jhs77_f_InGameDialogueLightPitchYaw = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldVector2>(MetaDefault, new BGId(5419589714363862926UL, 14735752373480144282UL), () => _ufle12jhs77_f_InGameDialogueLightPitchYaw = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_GameplayData;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_GameplayData => _ufle12jhs77_f_GameplayData ?? (_ufle12jhs77_f_GameplayData = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(4909705211094579299UL, 13210900775542928543UL), () => _ufle12jhs77_f_GameplayData = null));
	public List<Alias_rifegrt_Dialogues> RelatedDialoguesListUsingSegmentRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Dialogues>(Alias_rifegrt_Dialogues._f_Segment, Entity.Id);
	public List<Alias_rifegrt_SegmentsGameplayData> RelatedSegmentsGameplayDataListUsingSegmentRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_SegmentsGameplayData>(Alias_rifegrt_SegmentsGameplayData._f_Segment, Entity.Id);
	public List<Alias_rifegrt_Objects> RelatedObjectsListUsingOwnerRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Objects>(Alias_rifegrt_Objects._f_Owner, Entity.Id);
}
