using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Segments = E_Segments;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_SegmentsGameplayData")]
public partial class M_SegmentsGameplayData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint => MetaDefault;
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4989130159753333157UL,7118120055729332661UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public System.String f_name
	{
		get => _f_name[Entity.Index];
		set => _f_name[Entity.Index] = value;
	}
	public E_Segments f_Segment
	{
		get => (E_Segments) _f_Segment[Entity.Index];
		set => _f_Segment[Entity.Index] = value;
	}
	public System.Boolean f_Rescued
	{
		get => _f_Rescued[Entity.Index];
		set => _f_Rescued[Entity.Index] = value;
	}
	public System.Boolean f_AddedToSerpScreen
	{
		get => _f_AddedToSerpScreen[Entity.Index];
		set => _f_AddedToSerpScreen[Entity.Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name => _ufle12jhs77_f_name ?? (_ufle12jhs77_f_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5330384241163026195UL, 12595475573590950033UL), () => _ufle12jhs77_f_name = null));
	private static BansheeGz.BGDatabase.BGFieldRelationSingle _ufle12jhs77_f_Segment;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Segment => _ufle12jhs77_f_Segment ?? (_ufle12jhs77_f_Segment = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationSingle>(MetaDefault, new BGId(5163421334888915869UL, 10163773687724329907UL), () => _ufle12jhs77_f_Segment = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_Rescued;
	public static BansheeGz.BGDatabase.BGFieldBool _f_Rescued => _ufle12jhs77_f_Rescued ?? (_ufle12jhs77_f_Rescued = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4897271965161504167UL, 2768130027215449236UL), () => _ufle12jhs77_f_Rescued = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_AddedToSerpScreen;
	public static BansheeGz.BGDatabase.BGFieldBool _f_AddedToSerpScreen => _ufle12jhs77_f_AddedToSerpScreen ?? (_ufle12jhs77_f_AddedToSerpScreen = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5472508438153550995UL, 3271020857625076629UL), () => _ufle12jhs77_f_AddedToSerpScreen = null));
	public List<Alias_rifegrt_Segments> RelatedSegmentsListUsingGameplayDataRelation => BGCodeGenUtils.GetRelatedInbound<Alias_rifegrt_Segments>(Alias_rifegrt_Segments._f_GameplayData, Entity.Id);
}
