using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Segments = E_Segments;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_SegmentsGameplayData")]
public partial class M_SegmentsGameplayData : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4989130159753333157UL,7118120055729332661UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Segments f_Segment
	{
		get
		{
			return (E_Segments) _f_Segment[Entity.Index];
		}
		set
		{
			_f_Segment[Entity.Index] = value;
		}
	}
	public System.Boolean f_Rescued
	{
		get
		{
			return _f_Rescued[Entity.Index];
		}
		set
		{
			_f_Rescued[Entity.Index] = value;
		}
	}
	public System.Collections.Generic.List<System.Boolean> f_ObjDialoguePlayed
	{
		get
		{
			return _f_ObjDialoguePlayed[Entity.Index];
		}
		set
		{
			_f_ObjDialoguePlayed[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5330384241163026195UL,12595475573590950033UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Segment;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Segment
	{
		get
		{
			if(__f_Segment==null || __f_Segment.IsDeleted) __f_Segment=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5163421334888915869UL,10163773687724329907UL));
			return __f_Segment;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool __f_Rescued;
	public static BansheeGz.BGDatabase.BGFieldBool _f_Rescued
	{
		get
		{
			if(__f_Rescued==null || __f_Rescued.IsDeleted) __f_Rescued=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(4897271965161504167UL,2768130027215449236UL));
			return __f_Rescued;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldListBool __f_ObjDialoguePlayed;
	public static BansheeGz.BGDatabase.BGFieldListBool _f_ObjDialoguePlayed
	{
		get
		{
			if(__f_ObjDialoguePlayed==null || __f_ObjDialoguePlayed.IsDeleted) __f_ObjDialoguePlayed=(BansheeGz.BGDatabase.BGFieldListBool) MetaDefault.GetField(new BGId(5005048154492295582UL,18343704791617690790UL));
			return __f_ObjDialoguePlayed;
		}
	}
	private static readonly List<BGEntity> _tugjbyuhfv_reusableList = new List<BGEntity>();
	public List<E_Segments> RelatedSegmentsListUsingGameplayDataRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_Segments._f_GameplayData.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_Segments>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_Segments) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
}
