using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;
using Alias_rifegrt_Dialogues = E_Dialogues;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_Segments")]
public partial class M_Segments : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5644026291501976503UL,5194951680243965827UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public System.String f_SegmentName
	{
		get
		{
			return _f_SegmentName[Entity.Index];
		}
		set
		{
			_f_SegmentName[Entity.Index] = value;
		}
	}
	public UnityEngine.Object f_DialogueObject
	{
		get
		{
			return _f_DialogueObject[Entity.Index];
		}
	}
	public UnityEngine.Vector3 f_DialogueRotation
	{
		get
		{
			return _f_DialogueRotation[Entity.Index];
		}
		set
		{
			_f_DialogueRotation[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5670569073695034891UL,14796031301428454317UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString __f_SegmentName;
	public static BansheeGz.BGDatabase.BGFieldString _f_SegmentName
	{
		get
		{
			if(__f_SegmentName==null || __f_SegmentName.IsDeleted) __f_SegmentName=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4705691430409051370UL,10398669542945010076UL));
			return __f_SegmentName;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityObject __f_DialogueObject;
	public static BansheeGz.BGDatabase.BGFieldUnityObject _f_DialogueObject
	{
		get
		{
			if(__f_DialogueObject==null || __f_DialogueObject.IsDeleted) __f_DialogueObject=(BansheeGz.BGDatabase.BGFieldUnityObject) MetaDefault.GetField(new BGId(5042412784670426887UL,3798303333898769295UL));
			return __f_DialogueObject;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 __f_DialogueRotation;
	public static BansheeGz.BGDatabase.BGFieldVector3 _f_DialogueRotation
	{
		get
		{
			if(__f_DialogueRotation==null || __f_DialogueRotation.IsDeleted) __f_DialogueRotation=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(5760607302971462463UL,3672824699726006442UL));
			return __f_DialogueRotation;
		}
	}
	private static readonly List<BGEntity> _tugjbyuhfv_reusableList = new List<BGEntity>();
	public List<E_Dialogues> RelatedDialoguesListUsingSegmentRelation
	{
		get
		{
			var _private_related_list = Alias_rifegrt_Dialogues._f_Segment.GetRelatedIn(Entity.Id, _tugjbyuhfv_reusableList);
			if (_private_related_list.Count == 0) return null;
			var _private_result_list = new List<E_Dialogues>(_private_related_list.Count);
			for (var i = 0; i < _private_related_list.Count; i++) _private_result_list.Add((E_Dialogues) _private_related_list[i]);
			_tugjbyuhfv_reusableList.Clear();
			return _private_result_list;
		}
	}
}
