using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/M_ShortDialogues")]
public partial class M_ShortDialogues : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaNested _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaNested MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaNested>(new BGId(5585295301340535485UL,10436763047233263263UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Entity.Index];
		}
		set
		{
			_f_name[Entity.Index] = value;
		}
	}
	public E_Dialogues f_Dialogues
	{
		get
		{
			return (E_Dialogues) _f_Dialogues[Entity.Index];
		}
		set
		{
			_f_Dialogues[Entity.Index] = value;
		}
	}
	public UnityEngine.ScriptableObject f_ShortDialogue
	{
		get
		{
			return _f_ShortDialogue[Entity.Index];
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(__f_name==null || __f_name.IsDeleted) __f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5549575211351203337UL,14576254785773367446UL));
			return __f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldRelationSingle __f_Dialogues;
	public static BansheeGz.BGDatabase.BGFieldRelationSingle _f_Dialogues
	{
		get
		{
			if(__f_Dialogues==null || __f_Dialogues.IsDeleted) __f_Dialogues=(BansheeGz.BGDatabase.BGFieldRelationSingle) MetaDefault.GetField(new BGId(5310457040470112976UL,2937141984777347231UL));
			return __f_Dialogues;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldUnityScriptableObject __f_ShortDialogue;
	public static BansheeGz.BGDatabase.BGFieldUnityScriptableObject _f_ShortDialogue
	{
		get
		{
			if(__f_ShortDialogue==null || __f_ShortDialogue.IsDeleted) __f_ShortDialogue=(BansheeGz.BGDatabase.BGFieldUnityScriptableObject) MetaDefault.GetField(new BGId(4880749024170363498UL,9358360039208301971UL));
			return __f_ShortDialogue;
		}
	}
}
