using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class E_LevelData : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new E_LevelData(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new E_LevelData(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4612244309294333557UL,1881374458602735547UL));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String f_name
	{
		get
		{
			return _f_name[Index];
		}
		set
		{
			_f_name[Index] = value;
		}
	}
	public System.String f_Pin
	{
		get
		{
			return _f_Pin[Index];
		}
		set
		{
			_f_Pin[Index] = value;
		}
	}
	public System.String f_Biome
	{
		get
		{
			return _f_Biome[Index];
		}
		set
		{
			_f_Biome[Index] = value;
		}
	}
	public System.Int32 f_SceneIndex
	{
		get
		{
			return _f_SceneIndex[Index];
		}
		set
		{
			_f_SceneIndex[Index] = value;
		}
	}
	public System.String f_Level
	{
		get
		{
			return _f_Level[Index];
		}
		set
		{
			_f_Level[Index] = value;
		}
	}
	public System.Collections.Generic.List<System.String> f_UnlocksPins
	{
		get
		{
			return _f_UnlocksPins[Index];
		}
		set
		{
			_f_UnlocksPins[Index] = value;
		}
	}
	public System.Int32 f_LocksAmount
	{
		get
		{
			return _f_LocksAmount[Index];
		}
		set
		{
			_f_LocksAmount[Index] = value;
		}
	}
	public System.Boolean f_SegmentPresent
	{
		get
		{
			return _f_SegmentPresent[Index];
		}
		set
		{
			_f_SegmentPresent[Index] = value;
		}
	}
	public System.Int32 f_PinTextUI
	{
		get
		{
			return _f_PinTextUI[Index];
		}
		set
		{
			_f_PinTextUI[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_f_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _f_name
	{
		get
		{
			if(_ufle12jhs77_f_name==null || _ufle12jhs77_f_name.IsDeleted) _ufle12jhs77_f_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(4740419652275606489UL,16281884087163071164UL));
			return _ufle12jhs77_f_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Pin;
	public static BansheeGz.BGDatabase.BGFieldString _f_Pin
	{
		get
		{
			if(_ufle12jhs77_f_Pin==null || _ufle12jhs77_f_Pin.IsDeleted) _ufle12jhs77_f_Pin=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5682167220749758013UL,4951703566532017813UL));
			return _ufle12jhs77_f_Pin;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Biome;
	public static BansheeGz.BGDatabase.BGFieldString _f_Biome
	{
		get
		{
			if(_ufle12jhs77_f_Biome==null || _ufle12jhs77_f_Biome.IsDeleted) _ufle12jhs77_f_Biome=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5181998854119660587UL,4328844572943806389UL));
			return _ufle12jhs77_f_Biome;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_SceneIndex;
	public static BansheeGz.BGDatabase.BGFieldInt _f_SceneIndex
	{
		get
		{
			if(_ufle12jhs77_f_SceneIndex==null || _ufle12jhs77_f_SceneIndex.IsDeleted) _ufle12jhs77_f_SceneIndex=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5654346686901757335UL,3485210673166935936UL));
			return _ufle12jhs77_f_SceneIndex;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_f_Level;
	public static BansheeGz.BGDatabase.BGFieldString _f_Level
	{
		get
		{
			if(_ufle12jhs77_f_Level==null || _ufle12jhs77_f_Level.IsDeleted) _ufle12jhs77_f_Level=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(4793347658190675977UL,5994557562632312988UL));
			return _ufle12jhs77_f_Level;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldListString _ufle12jhs77_f_UnlocksPins;
	public static BansheeGz.BGDatabase.BGFieldListString _f_UnlocksPins
	{
		get
		{
			if(_ufle12jhs77_f_UnlocksPins==null || _ufle12jhs77_f_UnlocksPins.IsDeleted) _ufle12jhs77_f_UnlocksPins=(BansheeGz.BGDatabase.BGFieldListString) MetaDefault.GetField(new BGId(4805642874922064827UL,1960175709770092955UL));
			return _ufle12jhs77_f_UnlocksPins;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_LocksAmount;
	public static BansheeGz.BGDatabase.BGFieldInt _f_LocksAmount
	{
		get
		{
			if(_ufle12jhs77_f_LocksAmount==null || _ufle12jhs77_f_LocksAmount.IsDeleted) _ufle12jhs77_f_LocksAmount=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5389772333846653446UL,11461131677490296486UL));
			return _ufle12jhs77_f_LocksAmount;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_f_SegmentPresent;
	public static BansheeGz.BGDatabase.BGFieldBool _f_SegmentPresent
	{
		get
		{
			if(_ufle12jhs77_f_SegmentPresent==null || _ufle12jhs77_f_SegmentPresent.IsDeleted) _ufle12jhs77_f_SegmentPresent=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5708768082108931619UL,17251627778783522965UL));
			return _ufle12jhs77_f_SegmentPresent;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_f_PinTextUI;
	public static BansheeGz.BGDatabase.BGFieldInt _f_PinTextUI
	{
		get
		{
			if(_ufle12jhs77_f_PinTextUI==null || _ufle12jhs77_f_PinTextUI.IsDeleted) _ufle12jhs77_f_PinTextUI=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5447454200109153741UL,10343940833932085641UL));
			return _ufle12jhs77_f_PinTextUI;
		}
	}
	private static readonly E_LevelData.Factory _factory0_PFS = new E_LevelData.Factory();
	private E_LevelData() : base(MetaDefault)
	{
	}
	private E_LevelData(BGId id) : base(MetaDefault, id)
	{
	}
	private E_LevelData(BGMetaEntity meta) : base(meta)
	{
	}
	private E_LevelData(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static E_LevelData FindEntity(Predicate<E_LevelData> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((E_LevelData) entity)) as E_LevelData;
	}
	public static List<E_LevelData> FindEntities(Predicate<E_LevelData> filter, List<E_LevelData> result=null, Comparison<E_LevelData> sort=null)
	{
		result = result ?? new List<E_LevelData>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((E_LevelData) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((E_LevelData) e1, (E_LevelData) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((E_LevelData) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<E_LevelData> action, Predicate<E_LevelData> filter=null, Comparison<E_LevelData> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((E_LevelData) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((E_LevelData) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((E_LevelData)e1,(E_LevelData)e2));
	}
	public static E_LevelData GetEntity(BGId entityId)
	{
		return (E_LevelData) MetaDefault.GetEntity(entityId);
	}
	public static E_LevelData GetEntity(int index)
	{
		return (E_LevelData) MetaDefault[index];
	}
	public static E_LevelData GetEntity(string entityName)
	{
		return (E_LevelData) MetaDefault.GetEntity(entityName);
	}
	public static E_LevelData NewEntity()
	{
		return (E_LevelData) MetaDefault.NewEntity();
	}
}
#pragma warning restore 414
